### PR TITLE
Issue #1095: Spatial component should use floats for distance.

### PR DESCRIPTION
**Pull request by wu-edward**

### CODE REVIEW

**Comment by wu-edward** [comment]
Addresses #1095

**Comment by thomascorthals** [comment]
Minor nitpick: maybe update these tests to use `float`s? That should prevent the unlikely regression of accidentally reverting to `int`s.

https://github.com/solariumphp/solarium/blob/376ad9fdd56cb07f76a3b7c1dff6608b143d5c18/tests/Component/SpatialTest.php#L21

https://github.com/solariumphp/solarium/blob/376ad9fdd56cb07f76a3b7c1dff6608b143d5c18/tests/Component/SpatialTest.php#L65

https://github.com/solariumphp/solarium/blob/376ad9fdd56cb07f76a3b7c1dff6608b143d5c18/tests/Component/RequestBuilder/SpatialTest.php#L12

**Comment by wu-edward** [comment]
> Minor nitpick: maybe update these tests to use `float`s? That should prevent the unlikely regression of accidentally reverting to `int`s.
> 
> https://github.com/solariumphp/solarium/blob/376ad9fdd56cb07f76a3b7c1dff6608b143d5c18/tests/Component/SpatialTest.php#L21
> 
> https://github.com/solariumphp/solarium/blob/376ad9fdd56cb07f76a3b7c1dff6608b143d5c18/tests/Component/SpatialTest.php#L65
> 
> https://github.com/solariumphp/solarium/blob/376ad9fdd56cb07f76a3b7c1dff6608b143d5c18/tests/Component/RequestBuilder/SpatialTest.php#L12

Thanks for the review. Pushed a commit with updated tests.

**Review by thomascorthals — APPROVED** [review]

**Comment by thomascorthals** [comment]
@wu-edward I often forget this myself for small fixes like this, but it's worth mentioning in the `CHANGELOG` too. No longer rounding to an integer distance will influence results.

**Comment by wu-edward** [comment]
> @wu-edward I often forget this myself for small fixes like this, but it's worth mentioning in the `CHANGELOG` too. No longer rounding to an integer distance will influence results.

CHANGELOG updated

**Pull request merged**
