### PR TITLE
Update path to autoload.php for examples/ini.php

### PR DESCRIPTION
**Pull request by ismaeil**
Hi,
The examples in example folder use ini.php that includes the autoload file, but the path for it is not accurate no more.

### CODE REVIEW

**Comment by basdenooijer** [comment]
This path depends on the use case. The current path is correct for a 'standalone' solarium library. Your updated path matches when Solarium is installed as a Composer dependency.

I think both should be supported, but I need to look into what is the best way to do that.

**Comment by mkalkbrenner** [comment]
@ismaeil sorry for the late reply.

I think we should modify the code to rely on the composer driven autoloading.

**Comment by clemens-tolboom** [comment]
> I think we should modify the code to rely on the composer driven autoloading.

- Guess we can close this PR.

**Comment by mkalkbrenner** [comment]
I think, the commit of #659 addressed it

**Pull request closed without merging**
