### PR TITLE
Allow symfony/class-loader 3.0 to be installed

### PR DESCRIPTION
**Pull request by onigoetz**
Hi, here is my new pull request, and this time on the main repository.

### CODE REVIEW

**Comment by onigoetz** [comment]
Okay, it doesn't work.

I will get it to work and update the pull request once it works :)

**Comment by basdenooijer** [comment]
Ok, great!

**Comment by onigoetz** [comment]
Okay, I fixed it. It seems two deprecated methods were removed.
they're not needed anymore.

**Comment by basdenooijer** [comment]
Thanks for your work!

**Pull request merged**
