### PR TITLE
Fix: Properly indent build.xml

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] properly indents `build.xml`

### CODE REVIEW

**Comment by localheinz** [comment]
Thank you, @mkalkbrenner!

**Comment by thePanz** [comment]
@localheinz could you describe when (and why) the build.xml is used?

**Comment by localheinz** [comment]
@thePanz 

I assume it is used for http://ant.apache.org.

That is, I can confirm that it is not for https://www.phing.info - I just ran

```
$ composer global require phing/phing && phing
```

in the root of this project, and it failed with

```
Buildfile: /Users/am/Sites/solariumphp/solarium/build.xml

solarium > clean:

   [delete] Deleting directory /Users/am/Sites/solariumphp/solarium/build
    [mkdir] Created dir: /Users/am/Sites/solariumphp/solarium/${basedir}/build/api
    [mkdir] Created dir: /Users/am/Sites/solariumphp/solarium/${basedir}/build/code-browser
    [mkdir] Created dir: /Users/am/Sites/solariumphp/solarium/${basedir}/build/coverage
    [mkdir] Created dir: /Users/am/Sites/solariumphp/solarium/${basedir}/build/logs
    [mkdir] Created dir: /Users/am/Sites/solariumphp/solarium/${basedir}/build/pdepend

solarium > phpunit:


solarium > parallelTasks:


BUILD FAILED
/Users/am/Sites/solariumphp/solarium/build.xml:24:18: /Users/am/Sites/solariumphp/solarium/build.xml:25:38: Could not create task/type: 'antcall'. Make sure that this class has been declared using taskdef / typedef.

Total time: 0.1714 seconds
```

**Comment by thePanz** [comment]
Thanks @localheinz ! I guess we can safely remove this file! :)

**Pull request merged**
