### PR TITLE
zend framework is now called laminas

### PR DESCRIPTION
**Pull request by wickedOne**
replaced the zendframework/zend-http dev requirement with
laminas/laminas-http as zendframework is abandoned

### CODE REVIEW

**Comment by wickedOne** [comment]
fixed the style violation @ https://github.com/solariumphp/solarium/pull/738/commits/dfc42631b607bf949c69cfd820cb39652d1be6c6

after moving to 5.2 we might want to consider user deprecation for this namespace and rename it ``LaminasHttp`` or do you prefer dropping all custom adapters and implement #550 instead?

**Comment by mkalkbrenner** [comment]
> after moving to 5.2 we might want to consider user deprecation for this namespace and rename it LaminasHttp or do you prefer dropping all custom adapters and implement #550 instead?

What's your opinion about it? I hate to have multiple adapters. From my point of view, one would be enough. Isn't guzzle an abstraction already? but #550 might be OK as well.

**Comment by wickedOne** [comment]
back when those adapters were created it was great to support multiple clients, now with PSR-18 around i think #550 is the way to go. 

this way solarium no longer dictates the http client to be used in projects using solarium while we no longer have to maintain dependencies like in this pr: win win :-)

more than willing to give #550 a go in the near future which should be able to live amongst the current adapters which then can be deprecated in v6.x

what do you think?

**Comment by mkalkbrenner** [comment]
I agree!

**Comment by dmaicher** [comment]
This can be closed now that we have the `Psr18Adapter`, or? :blush:

**Pull request closed without merging**
