### PR TITLE
Basing off pull request 413, fixing tests

### PR DESCRIPTION
**Pull request by janusman**
Not sure how to give attribution to https://github.com/cristiroma ... I nevertheless wanted to test this with Travis and see if it worked at all.

### CODE REVIEW

**Comment by cristiroma** [comment]
@janusman do I need to do anything?

**Comment by janusman** [comment]
A code review of my changes would help :)

**Comment by acidaniel** [comment]
Any plan to accept this PR ?

**Comment by cristiroma** [comment]
@janusman I don't see any difference from #413, just the test case removed? I don't exactly understand, can you please help?

**Pull request merged**
