### PR TITLE
Do not parse collation array; values are already in name/value pairs.…

### PR DESCRIPTION
**Pull request by haydenyoung**
… Change unit test to match the collation data structure returned by Solr.

### CODE REVIEW

**Comment by basdenooijer** [comment]
Thanks for your PR. Changes look good, however I'm not certain this will work correctly with older versions of Solr. What version(s) did you test with?

**Comment by haydenyoung** [comment]
@basdenooijer Thanks for your feedback. Yes, you're right, I've been testing on v5 and v6 of Solr.

**Comment by haydenyoung** [comment]
@basdenooijer Would you like me to retest with an older version of Solr? E.g. Solr v4?

**Comment by basdenooijer** [comment]
that would be great, if we can confirm it works with the 4.x versions it can be merged.

**Comment by haydenyoung** [comment]
@basdenooijer I've just run ant phpunit against both my changed code and the original code in Solarium\Tests\QueryType\Select\ResponseParser\Component\SpellcheckTest. The original code is producing errors for solr4 and solr5:

`     [exec] 1) Solarium\Tests\QueryType\Select\ResponseParser\Component\SpellcheckTest::testParseExtended with data set "solr4" (array(array(array('delll', array(1, 0, 5, 0, array(array('dell', 1))), 'ultrashar', array(1, 6, 15, 0, array(array('ultrasharp', 1))), 'ultrashar', array(1, 16, 25, 0, array(array('ultrasharp', 1))), 'correctlySpelled', false, 'collation', array('dell ultrasharp', 0, array('delll', 'dell', 'ultrashar', 'ultrasharp')), 'collation', array('dell ultrasharp new', 0, array('delll', 'dell', 'ultrashar', 'ultrasharp'))))))
     [exec] Undefined offset: 0`

For the updated code in Spellcheck.php, there is neither an error for solr4 or solr5 data.

I just wanted to confirm this before changing code and testing further.

Thanks


Hayden

**Comment by haydenyoung** [comment]
@basdenooijer I'm going to add a version check and load the array depending on the solr version. Next question; how do I check for the currently running version of Solr from Solarium?

Thanks


Hayden

**Comment by haydenyoung** [comment]
Opening a new pull request with updated changes.

**Pull request closed without merging**
