### PR TITLE
Update Curl.php

### PR DESCRIPTION
**Pull request by dagnew**
Allow GET requests such as /select to validate in SOLR 5.1

### CODE REVIEW

**Comment by rmzamora** [comment]
This patch will only work if your doing GET but will throw an error for POST.

**Comment by dagnew** [comment]
In the end I went with:
      if (!isset($options['headers']['Content-Type'])) {
            if($method == 'GET'){
                $options['headers']['Content-Type'] = 'application/x-www-form-urlencoded; charset=utf-8';
            }else{
                $options['headers']['Content-Type'] = 'application/xml; charset=utf-8';
            }    
        }

**Comment by thomascorthals** [comment]
dagnew's code in the previous comment works for me as well. But to keep with the coding style, I suggest coding the check as ($method == Request::METHOD_GET) instead.

**Comment by lammensj** [comment]
I can confirm that the code of @dagnew works for me. It would be great if this gets merged.

**Comment by mfpierre** [comment]
If you're using NelmioSolariumBundle you can override the client adapter_class with a custom Curl class.

Here is an updated version of @dagnew's code
```php
if (!isset($options['headers']['Content-Type'])) {
    if($method == Request::METHOD_GET){
        $options['headers']['Content-Type'] = 'application/x-www-form-urlencoded; charset=utf-8';
    } else {
        $options['headers']['Content-Type'] = 'application/xml; charset=utf-8';
    }
}
```

**Comment by basdenooijer** [comment]
This PR still has the code that only works for GET requests, not the code mentioned in the comments that works for both GET and POST. 
If this gets updated and we can also confirm this works for solr < 5, I will merge it and create a new release.

**Comment by mfpierre** [comment]
I just made a new PR with the updated code to make this merged as quick as possible.

I can confirm on my side that it's working as well (solr 5.1)

**Comment by basdenooijer** [comment]
Closing this PR in favor of #334

**Pull request closed without merging**
