### PR TITLE
Integration test for Update query

### PR DESCRIPTION
**Pull request by thomascorthals**
Integration test for the current functionality of Update query, including raw XML commands.

### CODE REVIEW

**Comment by thomascorthals** [comment]
I had to move the rollback test to a seperate method with `@group solr_no_cloud` because it isn't supported in SolrCloud mode ([SOLR-4895](https://issues.apache.org/jira/browse/SOLR-4895)). This means some double setup work.

**Comment by thomascorthals** [comment]
> I had to move the rollback test to a seperate method with `@group solr_no_cloud` because it isn't supported in SolrCloud mode ([SOLR-4895](https://issues.apache.org/jira/browse/SOLR-4895)). This means some double setup work.

There's another way to check if we're testing a core or a collection without `@group`.

**Comment by wickedOne** [comment]
you can probably do an api call retrieving that information, but why would you want to do that? having two different groups for solr cloud and solr standalone sounds like a valid workflow to me.

**Comment by thomascorthals** [comment]
In this case, I don't like how I had to single out the rollback test in a different method with the `@group` approach. It felt like breaking up an integration into a smaller … unit. 😉 This seems like an elegant solution.
https://github.com/solariumphp/solarium/blob/a956603d270fc4edf241bd63b8d2c73f609d7bb6/tests/Integration/AbstractTechproductsTest.php#L459

**Pull request merged**
